[package]
name = "cntp_icon_tool_core"
version = "0.1.0"
edition = "2024"
license = "MIT"
keywords = ["cntp", "deployment"]
categories = ["development-tools"]
description = "Support library for generating Contempoary application icons"

[dependencies]
regex = "1"
